<?php

return [
    'ANT' => 'ANTIOQUIA',
    'ATL' => 'ATLÁNTICO',
    'BOG' => 'BOGOTÁ, D.C.',
    'BOL' => 'BOLÍVAR',
    'BOY' => 'BOYACÁ',
    'CAL' => 'CALDAS',
    'CAQ' => 'CAQUETÁ',
    'CAU' => 'CAUCA',
    'CES' => 'CESAR',
    'COR' => 'CÓRDOBA',
    'CUN' => 'CUNDINAMARCA',
    'CHO' => 'CHOCÓ',
    'HUI' => 'HUILA',
    'GUA' => 'GUAJIRA',
    'MAG' => 'MAGDALENA',
    'MET' => 'META',
    'NAR' => 'NARIÑO',
    'NOR' => 'NORTE DE SANTANDER',
    'QUI' => 'QUINDIO',
    'RIS' => 'RISARALDA',
    'SAN' => 'SANTANDER',
    'SUC' => 'SUCRE',
    'TOL' => 'TOLIMA',
    'VAL' => 'VALLE DEL CAUCA',
    'ARA' => 'ARAUCA',
    'CAS' => 'CASANARE',
    'PUT' => 'PUTUMAYO',
    'SAN' => 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA',
    'AMA' => 'AMAZONAS',
    'GUA' => 'GUAINÍA',
    'GUA' => 'GUAVIARE',
    'VAU' => 'VAUPÉS',
    'VIC' => 'VICHADA',
];
